output_dir: data/pipeline/batch_analysis
images: data/images/batch_analysis

output_map:
  preprocessing: data/pipeline/batch_analysis/preprocessing/dataset~{dataset}/file_id~{file_id}/preprocessed.zarr

DATASETS:
  
  batch_analysis_all:
    input:
      batch_analysis:
        HLCA: data/pipeline/load_data/download/HLCAv1_core.h5ad
      split_data:
        HLCA: data/pipeline/load_data/download/HLCAv1_core.h5ad
      marker_genes: split_data
    
    batch_analysis:
      sample: sample,donor_id,tissue_level_2,tissue_level_3
      n_permutations: 1000
      threads: 20
      highly_variable_genes:
        n_top_genes: 2000
      pca:
      covariates:
        - assay
        - dataset
        - study
        - donor_id
        - fresh_or_frozen
        - suspension_type
        - reference_genome
        - tissue_dissociation_protocol
        - tissue_level_2
        - tissue_level_3
        - tissue_sampling_method
        # - sample
        - total_counts
        - log10_total_counts
        - percent_mito
        - 3'_or_5
        - BMI
        - cell_ranger_version"
        - cell_viability_%
        - ethnicity
        - sample_type
        - sequencing_platform
        - sex
        - single_cell_platform
        - smoking_status
        - subject_type
        - subject_ID
        - anatomical_region_coarse
        - age_in_years
        - original_celltype_ann
        - Processing_site
    
    split_data:
      key: ann_finest_level
      values:
        - Alveolar_macrophages
        - AT2
        - Suprabasal
        - Basal_resting
        - Goblet_(nasal)
        - Multiciliated_(non-nasal)
        - CD8_T_cells
        - Monocyte-derived_Mph
        - Club_(nasal)
        - CD4_T_cells
        - Classical_monocytes
        - NK_cells
        - EC_general_capillary
        - Adventitial_fibroblasts
        - Club_(non-nasal)
        - DC2
        - Non-classical_monocytes
        - Alveolar_Mph_CCL3+
        - AT1
        - EC_arterial
        - EC_aerocyte_capillary
        - Mast_cells
        - EC_venous_systemic
        - EC_venous_pulmonary
        - Alveolar_fibroblasts
        - Multiciliated_(nasal)
        - Interstitial_Mph_perivascular
        - Hillock-like
        - B_cells
        - pre-TB_secretory
        - Lymphatic_EC_mature
        - Pericytes
        - Smooth_muscle
        - Plasma_cells
        - Goblet_(bronchial)
        - Peribronchial_fibroblasts
        - SMG_serous_(nasal)
        - AT0
        - SMG_serous_(bronchial)
        - SMG_duct
        - Alveolar_Mph_MT-positive
        - Alveolar_Mph_proliferating
        - Deuterosomal
        - AT2_proliferating
        - Goblet_(subsegmental)
        - Myofibroblasts
        - Lymphatic_EC_differentiating
        - Ionocyte
        - SM_activated_stress_response
        - Plasmacytoid_DCs
        - SMG_mucous
        - T_cells_proliferating
        - Smooth_muscle_FAM83D+
        - DC1
        - Migratory_DCs
        - Subpleural_fibroblasts
        - Mesothelium
        - Tuft
        - Neuroendocrine
        - Hematopoietic_stem_cells
        - Lymphatic_EC_proliferating

    marker_genes:
      layer: X
      sample: sample
      groups: dataset
      # marker_genes: HLCA_immune, HLCA_epithelial, HLCA_endothelial, HLCA_stroma, HLCA_other
      rank_genes_groups:
        reference: rest
        method: wilcoxon
      plot:
        n_genes: 10

  hlca_per_study:
    input:
      split_data:
        HLCA: data/pipeline/load_data/download/HLCAv1_core.h5ad
      preprocessing: split_data
      merge: preprocessing
      sample_representation: split_data, merge
      batch_analysis: split_data, sample_representation
    
    split_data:
      key: study
      values:
        - Banovich_Kropski_2020
        - Barbry_Leroy_2020
        - Jain_Misharin_2021
        - Krasnow_2020
        - Lafyatis_Rojas_2019
        - Meyer_2019
        - Misharin_2021
        - Misharin_Budinger_2018
        - Nawijn_2021
        - Seibold_2020
        - Teichmann_Meyer_2019
      dask: true
      backed: true
      threads: 50
    
    preprocessing:
      raw_counts: X
      normalize:
        target_sum: 10_000
      highly_variable_genes:
        n_top_genes: 2000
      assemble:
        - highly_variable_genes
        - pca
      colors:
        - assay
        - dataset
        - study
        - ann_level_1
        - ann_level_2
        - ann_level_3
        - ann_finest_level
        - majority_reference
        - qc_status
        - lung_condition
        - sex
        - scrublet_score
        - n_genes
        - n_counts
        - percent_mito

    merge:
      dask: true
      backed: true
      threads: 50
    
    sample_representation:
      sample_key: sample,donor_id,tissue_level_2,tissue_level_3
      raw_counts: layers/counts
      methods:
        pseudobulk:
      colors:
        - assay
        - dataset
        - study
        - donor_id
        - fresh_or_frozen
        - suspension_type
        - reference_genome
        - sequencing_platform
        - tissue_dissociation_protocol
        - tissue_level_2
        - tissue_level_3
        - tissue_sampling_method
    
    batch_analysis:
      sample: sample,donor_id,tissue_level_2,tissue_level_3
      n_permutations: 1000
      threads: 50
      highly_variable_genes:
        n_top_genes: 2000
      pca:
      covariates:
        - assay
        - dataset
        - study
        - donor_id
        - fresh_or_frozen
        - suspension_type
        - reference_genome
        - sequencing_platform
        - tissue_dissociation_protocol
        - tissue_level_2
        - tissue_level_3
        - tissue_sampling_method


  batch_correction:
    input:
      preprocessing:
        HLCA: data/pipeline/load_data/download/HLCAv1_core.h5ad
      integration: preprocessing
      clustering: integration
      label_transfer: clustering
      marker_genes: label_transfer
      metrics: marker_genes
      collect: metrics
      majority_voting: collect
    
    preprocessing:
      raw_counts: raw/X
      normalize:
        target_sum: 10_000
      highly_variable_genes:
        n_top_genes: 2000
      assemble:
        - highly_variable_genes
        - pca
      colors:
        - assay
        - dataset
        - study
        - ann_level_1
        - ann_level_2
        - ann_level_3
        - ann_finest_level
        - majority_reference
        - qc_status
        - lung_condition
        - sex
        - scrublet_score
        - n_genes
        - n_counts
        - percent_mito
    
    integration:
      raw_counts: layers/counts
      norm_counts: layers/normcounts
      var_mask: highly_variable
      neighbors:
        n_neighbors: 100
      batch:
        - sample
        - dataset
      label: scanvi_label
      output_types:
        - embed
      umap_colors:
        - assay
        - dataset
        - study
        - sample
        - donor_id
        - ann_level_1
        - ann_level_2
        - ann_level_3
        - ann_finest_level
        - majority_reference
        - qc_status
        - lung_condition
        - sex
        - scrublet_score
        - n_genes
        - n_counts
        - percent_mito
      methods:
        harmony_pytorch:
          n_comps: 50
          scale: false
        scvi:
          n_layers: 2
          n_latent: 30
          encode_covariates: True
          deeply_inject_covariates: False
          use_layer_norm: both
          use_batch_norm: none
          gene_likelihood: nb
          max_epochs: 100
          early_stopping: true
        scanvi:
          n_layers: 2
          n_latent: 30
          encode_covariates: True
          deeply_inject_covariates: False
          use_layer_norm: both
          use_batch_norm: none
          gene_likelihood: nb
          max_epochs: 100
          early_stopping: true
    
    metrics:
      unintegrated: layers/normcounts
      raw_counts: layers/counts
      var_mask: highly_variable
      overwrite_file_id: true
      weight_batch: 0.4
      label: scanvi_label
      batch:
        - dataset
        - sample
      gene_sets:
        Immune:
          - CD53
          - PTPRC
          - CORO1A
        Alveolar Mph:
          - CYP27A1
          - MARCO
          - FABP4
        T reg:
          - FOXP3
          - RTKN2
        Epithelial:
          - FXYD3
          - EPCAM
          - ELF3
        pre-TB secretory:
          - SCGB1A1 # from Tata paper
          - SFTPB
          - SCGB3A2
          - RNASE1
          - SFTA1P
        AT0:
          - SFTPB
          - SCGB3A2
          - IGFBP2
          - SERPINF1
          - TSPAN1
          - SFTA2
          - C11orf96
        EC:
          - CLDN5
          - ECSCR
          - CLEC14A
        Stroma:
          - COL1A2
          - DCN
          - MFAP4
        Hematopoietic stem cells:
          - CD53
          - PTPRC
          - CORO1A
          - CRHBP
          - SERPINE2
          - MAP7
      metrics:
        - nmi
        - ari
        - cell_cycle
        - clisi
        - ilisi
        - graph_connectivity
        - isolated_label_f1
        - pcr_comparison
        - morans_i_genes
        - kbet_pg
    
    marker_genes:
      sample: donor_id
      groups:
        - majority_reference
        - leiden_0.5_2
      marker_genes: HLCA_immune, HLCA_epithelial, HLCA_endothelial, HLCA_stroma, HLCA_other
      rank_genes_groups:
        reference: rest
        method: wilcoxon
      plot:
        n_genes: 10
      layer: layers/normcounts
    
    collect:
      sep: --
      same_slots:
        - X
        - var
        - layers
      merge_slots:
        - obs
        - obsm
        - obsp
        - uns
      skip_slots:
        - raw
    
    clustering:
      algorithm: leiden
      use_gpu: false
      neighbors:
        use_rep: X_emb
        n_neighbors: 100
        metric: euclidean
      resolutions:
        - 0.5
      hierarchy:
        2: 0.3
        3: 0.2
      umap_colors:
        - assay
        - dataset
        - study
        - ann_level_1
        - ann_level_2
        - ann_level_3
        - ann_finest_level
        - majority_reference
        - qc_status
        - lung_condition
        - sex
    
    label_transfer:
      majority_reference:
        reference_key: ann_finest_level
        query_key: leiden_0.5_3
        crosstab_kwargs:
          dropna: true
    
    majority_voting:
      columns:
        - majority_reference--.*

