output_dir: data/pipeline/HLCAv1/batch_analysis
images: data/images/HLCAv1/batch_analysis

funkyheatmap:
  group_col: integration_method
  scale: false
  scale_by_group: false

defaults:

  preprocessing:
    raw_counts: raw/X
    normalize:
      target_sum: 10_000
    highly_variable_genes:
      n_top_genes: 2000
      batch_key: dataset
      dask: true
    assemble:
      - normalize
      - highly_variable_genes
    colors:
      - assay
      - study
      - donor_id
      - tissue_level_2
      - tissue_level_3
      - tissue_sampling_method
      - n_counts
      - n_genes
      - percent_mito
      - cell_ranger_version
      - enrichment
      - ethnicity
      - sample_type
      - sequencing_platform
      - sex
      - subject_type
      - age_in_years
      - age_or_mean_of_age_range
      - original_celltype_ann
      - Processing_site
      - BMI
      - disease

  batch_analysis:
    sample: sample
    n_permutations: 1000
    max_threads: 4
    pca_plot:
      size: 50
    covariates:
      - assay
      - dataset
      - study
      - donor_id
      - fresh_or_frozen
      - suspension_type
      - tissue_dissociation_protocol
      - tissue_level_2
      - tissue_level_3
      - tissue_sampling_method
      # - sample
      - n_counts
      - n_genes
      - 3'_or_5
      - cell_ranger_version
      - enrichment
      - ethnicity
      - sample_type
      - sex
      - smoking_status
      - subject_type
      - anatomical_region_ccf_score
      - anatomical_region_coarse
      - anatomical_region_highest_res
      - anatomical_region_level_1
      - anatomical_region_level_2
      - anatomical_region_level_3
      - age_in_years
      # bio covariates
      - age_or_mean_of_age_range
      - BMI
      - disease
      - ann_finest_level
      - developmental_stage

  sample_representation:
    sample_key: sample
    methods:
      pseudobulk:
    colors:
      - Processing_site
      - age_in_years
      - age_or_mean_of_age_range
      - age_range
      - BMI
      - disease
      - smoking_status
      - subject_type
      - ann_level_1
      - ann_level_2
      - ann_level_3
      - ann_finest_level
      - majority_consensus
      - assay
      - dataset
      - study
      - donor_id
      - fresh_or_frozen
      - suspension_type
      - sequencing_platform
      - tissue_dissociation_protocol
      - tissue_level_2
      - tissue_level_3
      - tissue_sampling_method
      - sex
      - developmental_stage
      - n_counts
      - n_genes
      - percent_mito
      - cell_ranger_version
      - enrichment
      - ethnicity
      - sample_type

  clustering:
    algorithm: leiden
    use_gpu: false
    neighbors:
      use_rep: X_emb
      n_neighbors: 100
      metric: euclidean
    resolutions:
      - 0.5
    hierarchy:
      2: 0.3
      3: 0.2
    umap_colors:
      - assay
      - dataset
      - study
      - ann_level_1
      - ann_level_2
      - ann_level_3
      - ann_finest_level
      - majority_reference
      - qc_status
      - sex
      - tissue_level_2
      - tissue_level_3
  
  label_transfer:
    majority_reference:
      reference_key: ann_finest_level
      query_key: leiden_0.5_3
      crosstab_kwargs:
        dropna: true
  
  majority_voting:
      columns:
        - majority_reference--.*
