DATASETS:

  Reintegration_new_batch_covariate:

    input:
      relabel:
        HLCA: data/pipeline/HLCAv1/QC/merge/dataset~QC.zarr
      preprocessing: relabel
      integration: preprocessing
      clustering: integration
      metrics:
        harmony_dataset_new: data/pipeline/HLCAv1/batch_analysis/clustering/dataset~Reintegration_new_batch_covariate/file_id~integration:preprocessing:relabel:HLCA--integration=5bfa350bcd.zarr
        # harmony_dataset: data/pipeline/HLCAv1/batch_analysis/clustering/dataset~batch_correction/file_id~integration:preprocessing:HLCA--integration=00aba0f087.zarr
        # harmony_sample: data/pipeline/HLCAv1/batch_analysis/clustering/dataset~batch_correction/file_id~integration:preprocessing:HLCA--integration=f806260739.zarr
        scvi_dataset_new: data/pipeline/HLCAv1/batch_analysis/clustering/dataset~Reintegration_new_batch_covariate/file_id~integration:preprocessing:relabel:HLCA--integration=47ab10c6e1.zarr
        # scvi_dataset: data/pipeline/HLCAv1/batch_analysis/clustering/dataset~batch_correction/file_id~integration:preprocessing:HLCA--integration=95e7f6d559.zarr
        # scvi_sample: data/pipeline/HLCAv1/batch_analysis/clustering/dataset~batch_correction/file_id~integration:preprocessing:HLCA--integration=69b18c4fa7.zarr
        scanvi_dataset_new: data/pipeline/HLCAv1/batch_analysis/clustering/dataset~Reintegration_new_batch_covariate/file_id~integration:preprocessing:relabel:HLCA--integration=c5183445b8.zarr
        # scanvi_dataset: data/pipeline/HLCAv1/batch_analysis/clustering/dataset~batch_correction/file_id~integration:preprocessing:HLCA--integration=2e13d74e8f.zarr
        # scanvi_sample: data/pipeline/HLCAv1/batch_analysis/clustering/dataset~batch_correction/file_id~integration:preprocessing:HLCA--integration=f8c58c64b7.zarr
        # HLCAv1: data/pipeline/qc/metrics/dataset~benchmark/file_id~label_transfer:clustering:preprocessing:HLCA.zarr
      collect: metrics

      # per cell type effect of Processing_site
      filter: preprocessing
      split_data: filter
      marker_genes: split_data

    relabel:
      selective_update:
        base_column: dataset
        new_column: dataset_reintegration
        query: "study == 'Banovich_Kropski_2020'"
        update_map:
          Processing_site:
            TGen: Banovich_Kropski_2020_TGen
            VUMC: Banovich_Kropski_2020_VUMC

    preprocessing:
      highly_variable_genes:
        n_top_genes: 2000
        batch_key: dataset_reintegration
        dask: true

    integration:
      batch: dataset_reintegration

    filter:
      keep_by_column:
        study:
          - Banovich_Kropski_2020

    split_data:
      # fail_on_empty_subset: false
      key: ann_level_2
      values:
        - Myeloid
        - Alveolar_epithelium
        - Lymphoid
        - Blood_vessels
        - Airway_epithelium
        - Fibroblast_lineage
        - Lymphatic_EC
        - Smooth_muscle
        - Mesothelium
    
    marker_genes:
      layers: X
      groups: Processing_site
      plot:
        n_genes: 10

