DATASETS:
  
  batch_analysis_all:
    input:
      relabel:
        HLCA: data/pipeline/HLCAv1/QC/merge/dataset~QC.zarr
      preprocessing: relabel
      batch_analysis: preprocessing

    preprocessing:
      highly_variable_genes:
        n_top_genes: 2000
        dask: true
      assemble:
        - highly_variable_genes
        - pca

  batch_analysis_per_study:
    input:
      split_data:
        HLCA: data/pipeline/HLCAv1/batch_analysis/relabel/dataset~batch_analysis_all/file_id~HLCA.zarr
      preprocessing: split_data
      batch_analysis: preprocessing
    
    split_data:
      key: study
      values:
        - Banovich_Kropski_2020
        - Jain_Misharin_2021
        - Lafyatis_Rojas_2019
        - Seibold_2020
        # - Barbry_Leroy_2020
        # - Krasnow_2020
        # - Meyer_2019
        # - Misharin_2021
        # - Misharin_Budinger_2018
        # - Nawijn_2021
        # - Teichmann_Meyer_2019
      dask: true
      backed: true
      threads: 4
    
    preprocessing:
      highly_variable_genes:
        n_top_genes: 2000
      assemble:
        - highly_variable_genes
        - pca
    
    batch_analysis:
      pca_plot:
        size: 100
      n_permutations: 1000
      covariates:
        - assay
        - study
        - dataset
        - donor_id
        - anatomical_region_coarse
        - tissue_level_2
        - tissue_level_3
        - tissue_sampling_method
        - n_counts
        - n_genes
        - percent_mito
        - enrichment
        - ensembl_release_reference_genome
        - ethnicity
        - sample_type
        - sequencing_platform
        - sex
        - subject_type
        - age_in_years
        - age_or_mean_of_age_range
        - original_celltype_ann
        - Processing_site
        - BMI
        - disease
        - fresh_or_frozen
        - reference_genome
        - tissue_dissociation_protocol


  batch_correction:
    input:
      preprocessing:
        HLCA: data/pipeline/HLCAv1/QC/merge/dataset~QC.zarr
      integration: preprocessing
      clustering: integration
      label_transfer: clustering
      marker_genes: label_transfer
      metrics: marker_genes
      collect:
        harmony_dataset: data/pipeline/HLCAv1/batch_analysis/metrics/dataset~batch_correction/file_id~marker_genes:label_transfer:clustering:integration:preprocessing:HLCA--integration=00aba0f087.zarr
        harmony_sample: data/pipeline/HLCAv1/batch_analysis/metrics/dataset~batch_correction/file_id~marker_genes:label_transfer:clustering:integration:preprocessing:HLCA--integration=f806260739.zarr
        scvi_dataset: data/pipeline/HLCAv1/batch_analysis/metrics/dataset~batch_correction/file_id~marker_genes:label_transfer:clustering:integration:preprocessing:HLCA--integration=95e7f6d559.zarr
        scvi_sample: data/pipeline/HLCAv1/batch_analysis/metrics/dataset~batch_correction/file_id~marker_genes:label_transfer:clustering:integration:preprocessing:HLCA--integration=69b18c4fa7.zarr
        scanvi_dataset: data/pipeline/HLCAv1/batch_analysis/metrics/dataset~batch_correction/file_id~marker_genes:label_transfer:clustering:integration:preprocessing:HLCA--integration=2e13d74e8f.zarr
        scanvi_sample: data/pipeline/HLCAv1/batch_analysis/metrics/dataset~batch_correction/file_id~marker_genes:label_transfer:clustering:integration:preprocessing:HLCA--integration=f8c58c64b7.zarr
        HLCAv1: data/pipeline/qc/metrics/dataset~benchmark/file_id~label_transfer:clustering:preprocessing:HLCA.zarr
      majority_voting: collect

    preprocessing:
      colors:
        - assay
        - dataset
        - study
        - ann_level_1
        - ann_level_2
        - ann_level_3
        - ann_finest_level
        - scanvi_label
        - qc_status
        - lung_condition
        - sex
        - scrublet_score
        - doubletdetection_score
        - n_genes
        - n_counts
        - percent_mito


    integration:
      batch:
        - dataset
        - sample

    marker_genes:
      groups:
        - majority_reference
        - leiden_0.5_2
    
    metrics:
      funkyheatmap:
        group_col: integration_method


  batch_correction_pseudobulk:
    input:
      sample_representation:
        HLCA: data/pipeline/HLCAv1/batch_analysis/majority_voting/dataset~batch_correction/file_id~collect:batch_correction.zarr
      collect:
        harmony_sample: data/pipeline/HLCAv1/batch_analysis/sample_representation/dataset~batch_correction_pseudobulk/file_id~HLCA/input_type~embed/method~pseudobulk--hyperparams~None--var_mask~None--use_rep~obsm/X_emb--harmony_sample.zarr
        harmony_dataset: data/pipeline/HLCAv1/batch_analysis/sample_representation/dataset~batch_correction_pseudobulk/file_id~HLCA/input_type~embed/method~pseudobulk--hyperparams~None--var_mask~None--use_rep~obsm/X_emb--harmony_dataset.zarr
        scvi_sample: data/pipeline/HLCAv1/batch_analysis/sample_representation/dataset~batch_correction_pseudobulk/file_id~HLCA/input_type~embed/method~pseudobulk--hyperparams~None--var_mask~None--use_rep~obsm/X_emb--scvi_sample.zarr
        scvi_dataset: data/pipeline/HLCAv1/batch_analysis/sample_representation/dataset~batch_correction_pseudobulk/file_id~HLCA/input_type~embed/method~pseudobulk--hyperparams~None--var_mask~None--use_rep~obsm/X_emb--scvi_dataset.zarr
        scanvi_sample: data/pipeline/HLCAv1/batch_analysis/sample_representation/dataset~batch_correction_pseudobulk/file_id~HLCA/input_type~embed/method~pseudobulk--hyperparams~None--var_mask~None--use_rep~obsm/X_emb--scanvi_sample.zarr
        scanvi_dataset: data/pipeline/HLCAv1/batch_analysis/sample_representation/dataset~batch_correction_pseudobulk/file_id~HLCA/input_type~embed/method~pseudobulk--hyperparams~None--var_mask~None--use_rep~obsm/X_emb--scanvi_dataset.zarr
    
    sample_representation:
      dask: false
      use_rep:
        - obsm/X_emb--harmony_sample
        - obsm/X_emb--harmony_dataset
        - obsm/X_emb--scvi_sample
        - obsm/X_emb--scvi_dataset
        - obsm/X_emb--scanvi_sample
        - obsm/X_emb--scanvi_dataset
      
    collect:
      sep: --
      same_slots:
        - X
        - var
        - layers
      merge_slots:
        - obs
        - obsm
      skip_slots:
        - raw
