DATASETS:

  prepare_data:
    input:
      filter:
        All: data/input/hca_out/relabel/dataset~Benchmark_prepare_data/file_id~All.zarr
      split_data: filter
    
    filter:
      subset: true
      dask: true
      backed: true
      remove_by_column:
        qc_status:
          - failed


  per_lineage:
    input:
      preprocessing:
        B_plasma: "data/pipeline/feature_selection/HICA/split_data/dataset~prepare_data/file_id~filter:All/\
          key~lineage/value~B_plasma.zarr"
        Myeloid: "data/pipeline/feature_selection/HICA/split_data/dataset~prepare_data/file_id~filter:All/\
          key~lineage/value~Myeloid.zarr"
        Other: "data/pipeline/feature_selection/HICA/split_data/dataset~prepare_data/file_id~filter:All/\
          key~lineage/value~Other.zarr"
        TCD4: "data/pipeline/feature_selection/HICA/split_data/dataset~prepare_data/file_id~filter:All/\
          key~lineage/value~TCD4.zarr"
        TCD8_NK: "data/pipeline/feature_selection/HICA/split_data/dataset~prepare_data/file_id~filter:All/\
          key~lineage/value~TCD8_NK.zarr"
      integration: preprocessing
      clustering: integration
      label_transfer: clustering
    
    clustering:
      resolutions: 1.0
      hierarchy:
        2: 0.3
        3: 0.2
    
    label_transfer:
      majority_reference:
        reference_key: celltypist_Healthy_COVID19_PBMC:majority_voting
        query_key: leiden_1.0_3
        crosstab_kwargs:
          dropna: true


  global:
    input:
      preprocessing:
        All: data/pipeline/feature_selection/HICA/filter/dataset~prepare_data/file_id~All.zarr
      integration: preprocessing
      split_data: integration
      metrics: integration,split_data
      clustering: integration
      label_transfer: clustering
      collect: label_transfer
      majority_voting: collect
    
    clustering:
      recompute_umap: true
      recompute_neighbors: true
      resolutions: 1.0
      hierarchy:
        2: 0.5
        3: 0.2
    
    label_transfer:
      majority_reference:
        reference_key: celltypist_Healthy_COVID19_PBMC:majority_voting
        query_key: leiden_1.0_3
        crosstab_kwargs:
          dropna: true
    
    majority_voting:
      columns:
        - majority_reference--.*


  # B_collect:
  #   input:
  #     metrics:
  #        # unintegrated
  #         integration=unintegrated--strategy=lineage: "data/pipeline/feature_selection/HICA/label_transfer/dataset~per_lineage/\
  #           file_id~clustering:integration:preprocessing:B_cells--integration=b6db15edb2.zarr"
  #         integration=unintegrated--strategy=global: "data/pipeline/feature_selection/HICA/split_data/dataset~global/\
  #           file_id~label_transfer:clustering:integration:preprocessing:All--integration=b6db15edb2/key~lineage/value~B_cells.zarr"
  #         # harmony
  #         integration=harmony_scaled--strategy=lineage: "data/pipeline/feature_selection/HICA/label_transfer/dataset~per_lineage/\
  #           file_id~clustering:integration:preprocessing:B_cells--integration=8db25de1ea.zarr"
  #         integration=harmony_scaled--strategy=global: "data/pipeline/feature_selection/HICA/label_transfer/dataset~global/\
  #           file_id~label_transfer:clustering:integration:preprocessing:All--integration=8db25de1ea/key~lineage/value~B_cells.zarr"
  #         integration=harmony_unscaled--strategy=lineage: "data/pipeline/feature_selection/HICA/label_transfer/dataset~per_lineage/\
  #           file_id~clustering:integration:preprocessing:B_cells--integration=8e0d2946c2.zarr"
  #         integration=harmony_unscaled--strategy=global: "data/pipeline/feature_selection/HICA/label_transfer/dataset~global/\
  #           file_id~label_transfer:clustering:integration:preprocessing:All--integration=8e0d2946c2/key~lineage/value~B_cells.zarr"
  #         # scvi
  #         integration=scvi_30--strategy=lineage: "data/pipeline/feature_selection/HICA/clustering/dataset~per_lineage/\
  #           file_id~integration:preprocessing:B_cells--integration=dcf9672da4.zarr"
  #         integration=scvi_30--strategy=global: "data/pipeline/feature_selection/HICA/split_data/dataset~global/\
  #           file_id~label_transfer:clustering:integration:preprocessing:All--integration=c3388d9dea/key~lineage/value~B_cells.zarr"
  #         integration=scvi_128--strategy=lineage: "data/pipeline/feature_selection/HICA/clustering/dataset~per_lineage/\
  #           file_id~integration:preprocessing:B_cells--integration=51114673bc.zarr"
  #         integration=scvi_128--strategy=global: "data/pipeline/feature_selection/HICA/split_data/dataset~global/\
  #           file_id~label_transfer:clustering:integration:preprocessing:All--integration=0dc489f4a5/key~lineage/value~B_cells.zarr"
  #         # drvi
  #         integration=drvi--strategy=lineage: "data/pipeline/feature_selection/HICA/clustering/dataset~per_lineage/\
  #           file_id~integration:preprocessing:B_cells--integration=8549126649.zarr"
  #         integration=drvi--strategy=global: "data/pipeline/feature_selection/HICA/split_data/dataset~global/\
  #           file_id~label_transfer:clustering:integration:preprocessing:All--integration=8549126649/key~lineage/value~B_cells.zarr"
  #         # scpoli
  #         integration=scpoli--strategy=lineage: "data/pipeline/feature_selection/HICA/clustering/dataset~per_lineage/\
  #           file_id~integration:preprocessing:B_cells--integration=8f942f4628.zarr"
  #         integration=scpoli--strategy=global: "data/pipeline/feature_selection/HICA/split_data/dataset~global/\
  #           file_id~label_transfer:clustering:integration:preprocessing:All--integration=8f942f4628/key~lineage/value~B_cells.zarr"
  #     marker_genes: metrics
  #     collect: marker_genes
  #     majority_voting: collect
  #   metrics:
  #     gene_sets: B
  #   majority_voting:
  #     columns:
  #       - majority_reference--.*
