defaults:
  doublets:
    counts: raw/X
    batch: sample
    chunk_size: 20000
  
  split_data:
    dask: true
    backed: true
    key: ann_level_1
    values:
      - Immune
      - Epithelial
      - Endothelial
      - Stroma
   
  qc:
    counts: X
    hue:
      - ann_level_1
      - ann_level_2
      - ann_level_3
      - ann_finest_level
      - scanvi_label
      - assay
      - dataset
      - study
      - donor_id
      - fresh_or_frozen
      - sex
      - lung_condition
      - reference_genome
      - sequencing_platform
      - smoking_status
      - subject_type
      - tissue_dissociation_protocol
      - doubletdetection_score
      - scrublet_score
  
  merge:
    merge_strategy: inner
    slots:
        X: X
        obs: obs
        var: var
    dask: true
    backed: true
    threads: 50
  
  preprocessing:
    raw_counts: X
    normalize:
      target_sum: 10_000
    highly_variable_genes:
      n_top_genes: 2000
      batch_key: dataset
    extra_hvgs:
      overwrite_args:
        n_top_genes: 2000
        batch_key: dataset
      union_over: ann_level_1
    assemble:
      - normalize
      - highly_variable_genes
      - extra_hvgs
    colors:
      - assay
      - dataset
      - study
      - ann_level_1
      - ann_level_2
      - ann_level_3
      - ann_finest_level
      - scanvi_label
      - majority_reference
      - qc_status
      - lung_condition
      - sex
      - scrublet_score
      - n_genes
      - n_counts
      - percent_mito
  
  integration:
    raw_counts: layers/counts
    norm_counts: layers/normcounts
    var_mask:
      - extra_hvgs--batch_key=dataset--n_top_genes=2000
    neighbors:
      n_neighbors: 100
    batch: dataset
    output_types:
      - embed
    umap_colors:
      - assay
      - dataset
      - study
      - ann_level_1
      - ann_level_2
      - ann_level_3
      - ann_finest_level
      - scanvi_label
      - majority_reference
      - qc_status
      - lung_condition
      - sex
      - scrublet_score
      - n_genes
      - n_counts
      - percent_mito
    methods:
      unintegrated:
      harmony_pytorch:
        n_comps: 50
        scale: true
      scvi:
        n_latent: 30
        n_hidden: 128
        n_layers: 2
        dispersion: gene-batch
        dropout_rate: 0.2
        early_stopping: true
        max_epochs: 50
        use_observed_lib_size: true
        categorical_covariate_keys:
          - # no categorical covariates
          - [assay] # additionally correct for
      drvi:
        n_latent: 128
        encoder_dims:
          - [128, 128]
        decoder_dims:
          - [128, 128]
        max_epochs: 50
        early_stopping: true
      scpoli:
        cell_type_keys: # unsupervised
        embedding_dims: 128
        recon_loss: nb
        n_epochs: 50
        unlabeled_prototype_training: false
        eta: 0.3
  
  clustering:
    algorithm: leiden
    use_gpu: true
    neighbors:
      use_rep: X_emb
      n_neighbors: 100
      metric: euclidean
    resolutions:
      - 1.0
    hierarchy:
      2: 0.5
      3: 0.2
    umap_colors:
      - assay
      - dataset
      - study
      - ann_level_1
      - ann_level_2
      - ann_level_3
      - ann_finest_level
      - scanvi_label
      - majority_reference
      - qc_status
      - lung_condition
      - sex
      - scrublet_score
      - n_genes
      - n_counts
      - percent_mito
    # Immmune:
      - CD53
      - PTPRC
      - CORO1A
    # Monocytes:
      - FCER1G
      - C1orf162
      - CLEC7A
    # Classical monocytes:
      - S100A12
      - FCN1
      - RNASE2
    # Non-classical monocytes:
      - MTSS1
      - LILRA5
      - FCN1
    # DC1:
      - XCR1
      - CLEC9A
      - CLNK
    # DC2:
      - PKIB
      - CLEC10A
      - CD1E
    # Plasmacytoid DCs:
      - SCT
      - SMPD3
      - LILRA4
    # Migratory DCs:
      - LAD1
      - CCL19
    # Alveolar macrophages:
      - CYP27A1
      - MARCO
      - FABP4
    # Alveolar Mph CCL3+:
      - CCL20
      - FAM89A
    # Alveolar Mph MT-positive:
      - MT1M
      - CCL18
      - MT1E
    # Alveolar Mph proliferating:
      - TYMS
      - CENPW
      - MND1
    # Interstitial Mph perivascular:
      - F13A1
      - FOLR2
    # Monocyte-derived Mph:
      - SPP1
      - HAMP
    # Mast cells:
      - MS4A2
      - SLC18A2
      - RGS13
    # B cell:
      - MS4A1
      - CD79A
    # B naive:
      - TCL1A
      - IGHM
      - IGHD
    # B memory:
      - CD27
      - TNFRSF13B
    # Plasma cells:
      - MZB1
      - JCHAIN
      - TNFRSF17
      - ITM2C
      - DERL3
      - POU2AF1
      - IGHA1 # (Igs)
      - TXNDC11
      - CD79A
    # T cell:
      - ISG20
      - CCL5
    # T cell CD4:
      - CD40LG
      - TNFRSF25
      - CD28
      - CD4
      - TRAT1
    # T cell CD8:
      - CD8A
      - CD8B
      - TRGC2
    # NK cells:
      - GNLY
      - SPON2
      - FCGR3A
    # T cells proliferating:
      - CENPW
      - TK1
      - MKI67
  # HLCA_epithelial:
    # Epithelial:
      - FXYD3
      - EPCAM
      - ELF3
    # AT:
      - SFTA2
      - SLC39A8
      - HOPX
    # pre-TB secretory:
      - SCGB1A1 # from Tata paper
      - SFTPB
      - SCGB3A2
      - RNASE1
      - SFTA1P
    # AT0:
      - SFTPB
      - SCGB3A2
      - IGFBP2
      - SERPINF1
      - TSPAN1
      - SFTA2
    # AT1:
      - CLIC5
      - SPOCK2
      - TIMP3
    # AT2:
      - MFSD2A
      - C8orf4
      - C11orf96
    # AT2 proliferating:
      - CENPW
      - CDKN3
      - BIRC5
    # Ciliated:
      - IGFBP2
      - SERPINF1
      - TSPAN1
    # Basal resting:
      - KRT15
      - KRT17
      - TP63
    # Club (nasal):
      - SERPINB3
      - TCN1
      - ASRGL1
    # Club (non-nasal):
      - CYP2F1
      - SCGB3A1
      - BPIFB1
    # Deuterosomal:
      - CDC20B
      - KDELC2
      - E2F7
    # Goblet (bronchial):
      - GPX8
      - ALDH1A3
      - CEACAM5
    # Goblet (nasal):
      - CEACAM5
      - LYPD2
      - PSCA
    # Goblet (subsegmental):
      - BPIFB1
      - C16orf89
      - NPDC1
    # Hillock-like:
      - DSG3
      - RAB38
      - TNS4
    # Multiciliated (nasal):
      - BEST4
      - LYPD2
    # Multiciliated (non-nasal):
      - RSPH1
      - C20orf85
      - C9orf24
    # Tuft:
      - DAB1
    # Ionocyte:
      - BSND
      - IGF1
      - CLCNKB
  # HLCA_endothelial:
    # EC:
      - CLDN5
      - ECSCR
      - CLEC14A
    # EC aerocyte capillary:
      - SOSTDC1
    # EC arterial:
      - DKK2
      - IGFBP3
    # EC general capillary:
      - SPARCL1
      - AQP1
      - RNASE1
      - IL7R
      - FCN3
      - MT1M
    # EC venous:
      - SPARCL1
      - AQP1
      - RNASE1
    # EC venous pulmonary:
      - CPE
      - C7
      - MMRN1
    # EC venous systemic:
      - TPD52L1
      - ZNF385D
      - OLFM1
    # Lymphatic EC:
      - CCL21
      - TFF3
      - MMRN1
    # Lymphatic EC differentiating:
      - PROX1
      - PKHD1L1
      - FLT4
      - SEMA3D
    # Lymphatic EC mature:
      - LYVE1
      - CCL21
    # Lymphatic EC proliferating:
      - MKI67
      - TOP2A
  # HLCA_stroma:
    # Stroma:
      - COL1A2
      - DCN
      - MFAP4
    # Fibroblasts:
      - LUM
      - COL6A3
      - CFD
    # Adventitial fibroblasts:
      - MFAP5
      - SCARA5
      - PI16
    # Alveolar fibroblasts:
      - SPINT2
      - LIMCH1
      - FGFR4
    # Subpleural fibroblasts:
      - MARCKSL1
      - APOC1
      - MMP23B
    # Peribronchial fibroblasts:
      - COL15A1
      - CXCL14
      - DIO2
    # Pericytes:
      - LAMC3
    # Myofibroblasts:
      - LMOD1
      - ATP1B1
      - TYRP1
    # Smooth muscle:
      - MYH11
      - TINAGL1
      - PLN
    # SM FAM83D+:
      - FAM83D
    # SM activated stress response:
      - EGR1
      - FOSB
      - ATF3
    # Submucosal Gland Myoepithelial:
      - FXYD3
      - EPCAM
      - ELF3
      - TCN1
      - FAM3D
    # SMG duct:
      - CCL28
      - MGST1
      - KRT19
      - KLF5
    # SMG mucous:
      - CCL28
      - BPIFB2
      - MUC5B
      - NKX3-1
    # SMG serous (bronchial):
      - CCL28
      - RP11-1143G9.4
      - S100A1
      - PRB3
    # SMG serous (nasal):
      - CCL28
      - STATH
      - ODAM
      - MUC7
    # Suprabasal:
      - IGFBP2
      - SERPINF1
      - TSPAN1
      - KRT5
      - SERPINB3
    # Mesothelium:
      - KLK11
      - UPK3B
      - ITLN1
  # HLCA_other:
    # Hematopoietic stem cells:
      - CD53
      - PTPRC
      - CORO1A
      - CRHBP
      - SERPINE2
      - MAP7
    # Neuroendocrine:
      - CELF3
      - SLC6A17
      - CDK5R2
  
  marker_genes:
    sample: donor_id
    groups:
        - leiden_1.0_1
    #     - leiden_1.0_2
    marker_genes: HLCA_immune, HLCA_epithelial, HLCA_endothelial, HLCA_stroma, HLCA_other
    rank_genes_groups:
      reference: rest
      method: wilcoxon
    plot:
      n_genes: 20
    layer: layers/normcounts
  
  metrics:
    unintegrated: layers/normcounts
    raw_counts: layers/counts
    var_mask: highly_variable
    overwrite_file_id: true
    weight_batch: 0.3
    label: scanvi_label
    batch:
      - dataset
      # - assay
    covariates:
      - disease
      - percent_mito
      - scrublet_score
    metrics:
      - nmi
      - ari
      # - asw_label
      # - asw_batch
      - cell_cycle
      - clisi
      - ilisi
      - graph_connectivity
      - isolated_label_f1
      - pcr_comparison
      # - morans_i
      - morans_i_genes
      # - pcr
      # - pcr_genes
      - kbet_pg
  
  collect:
    # obs_index_col:
    #   .*=lineage: obs_names_before_qc_per_study
    #   .*=global: obs_names_before_qc_per_study
    sep: --
    same_slots:
      - X
      - var
      - layers
    merge_slots:
      - obs
      - obsm
      - obsp
      - uns
    skip_slots:
      - raw
