AT0:
- SFTPB
- SCGB3A2
- SFTA2
- IGFBP2
- SERPINF1
- TSPAN1
- FXYD3
- EPCAM
- ELF3
AT1:
- CLIC5
- SPOCK2
- TIMP3
- HOPX
- SFTA2
- SLC39A8
- FXYD3
- EPCAM
- ELF3
AT2:
- MFSD2A
- C8orf4
- C11orf96
- HOPX
- SFTA2
- SLC39A8
- FXYD3
- EPCAM
- ELF3
AT2 proliferating:
- CENPW
- CDKN3
- BIRC5
- HOPX
- SFTA2
- SLC39A8
- FXYD3
- EPCAM
- ELF3
Adventitial fibroblasts:
- MFAP5
- SCARA5
- PI16
- LUM
- COL6A3
- CFD
- COL1A2
- DCN
- MFAP4
Alveolar Mph CCL3+:
- CCL20
- FAM89A
- CD53
- PTPRC
- CORO1A
- FCER1G
- C1orf162
- CLEC7A
Alveolar Mph MT-positive:
- MT1M
- CCL18
- MT1E
- CD53
- PTPRC
- CORO1A
- FCER1G
- C1orf162
- CLEC7A
Alveolar Mph proliferating:
- TYMS
- CENPW
- MND1
- CD53
- PTPRC
- CORO1A
- FCER1G
- C1orf162
- CLEC7A
Alveolar fibroblasts:
- SPINT2
- LIMCH1
- FGFR4
- LUM
- COL6A3
- CFD
- COL1A2
- DCN
- MFAP4
Alveolar macrophages:
- CYP27A1
- MARCO
- FABP4
- CD53
- PTPRC
- CORO1A
- FCER1G
- C1orf162
- CLEC7A
B cells:
- MS4A1
- CD53
- PTPRC
- CORO1A
Basal resting:
- IGFBP2
- SERPINF1
- TSPAN1
- KRT15
- KRT17
- TP63
- FXYD3
- EPCAM
- ELF3
CD4 T cells:
- CD40LG
- TNFRSF25
- CD28
- CD4
- TRAT1
- CD53
- PTPRC
- CORO1A
- ISG20
- CCL5
CD8 T cells:
- CD8A
- CD8B
- TRGC2
- CD53
- PTPRC
- CORO1A
- ISG20
- CCL5
Classical monocytes:
- S100A12
- FCN1
- RNASE2
- CD53
- PTPRC
- CORO1A
- FCER1G
- C1orf162
- CLEC7A
Club (nasal):
- IGFBP2
- SERPINF1
- TSPAN1
- SERPINB3
- TCN1
- ASRGL1
- FXYD3
- EPCAM
- ELF3
Club (non-nasal):
- IGFBP2
- SERPINF1
- TSPAN1
- CYP2F1
- SCGB3A1
- BPIFB1
- FXYD3
- EPCAM
- ELF3
DC1:
- XCR1
- CLEC9A
- CLNK
- CD53
- PTPRC
- CORO1A
DC2:
- PKIB
- CLEC10A
- CD1E
- CD53
- PTPRC
- CORO1A
- FCER1G
- C1orf162
- CLEC7A
Deuterosomal:
- IGFBP2
- SERPINF1
- TSPAN1
- CDC20B
- KDELC2
- E2F7
- FXYD3
- EPCAM
- ELF3
EC aerocyte capillary:
- SOSTDC1
- CLDN5
- ECSCR
- CLEC14A
EC arterial:
- DKK2
- IGFBP3
- CLDN5
- ECSCR
- CLEC14A
EC general capillary:
- SPARCL1
- AQP1
- RNASE1
- IL7R
- FCN3
- MT1M
- CLDN5
- ECSCR
- CLEC14A
EC venous pulmonary:
- SPARCL1
- AQP1
- RNASE1
- CPE
- C7
- MMRN1
- CLDN5
- ECSCR
- CLEC14A
EC venous systemic:
- SPARCL1
- AQP1
- RNASE1
- TPD52L1
- ZNF385D
- OLFM1
- CLDN5
- ECSCR
- CLEC14A
Goblet (bronchial):
- IGFBP2
- SERPINF1
- TSPAN1
- FXYD3
- EPCAM
- ELF3
- GPX8
- ALDH1A3
- CEACAM5
Goblet (nasal):
- IGFBP2
- SERPINF1
- TSPAN1
- FXYD3
- EPCAM
- ELF3
- CEACAM5
- LYPD2
- PSCA
Goblet (subsegmental):
- IGFBP2
- SERPINF1
- TSPAN1
- FXYD3
- EPCAM
- ELF3
- BPIFB1
- C16orf89
- NPDC1
Hematopoietic stem cells:
- CRHBP
- SERPINE2
- MAP7
- CD53
- PTPRC
- CORO1A
Hillock-like:
- IGFBP2
- SERPINF1
- TSPAN1
- FXYD3
- EPCAM
- ELF3
- DSG3
- RAB38
- TNS4
Interstitial Mph perivascular:
- CD53
- PTPRC
- CORO1A
- F13A1
- FOLR2
- FCER1G
- C1orf162
- CLEC7A
Ionocyte:
- FXYD3
- EPCAM
- ELF3
- BSND
- IGF1
- CLCNKB
Lymphatic EC differentiating:
- CLDN5
- ECSCR
- CLEC14A
- CCL21
- TFF3
- MMRN1
- PROX1
- PKHD1L1
- FLT4
- SEMA3D
Lymphatic EC mature:
- CLDN5
- ECSCR
- CLEC14A
- CCL21
- TFF3
- MMRN1
- LYVE1
- CCL21
Lymphatic EC proliferating:
- CLDN5
- ECSCR
- CLEC14A
- MKI67
- TOP2A
Mast cells:
- CD53
- PTPRC
- CORO1A
- MS4A2
- SLC18A2
- RGS13
Mesothelium:
- KLK11
- UPK3B
- ITLN1
- COL1A2
- DCN
- MFAP4
Migratory DCs:
- CD53
- PTPRC
- CORO1A
- LAD1
- CCL19
Monocyte-derived Mph:
- CD53
- PTPRC
- CORO1A
- SPP1
- HAMP
- FCER1G
- C1orf162
- CLEC7A
Multiciliated (nasal):
- IGFBP2
- SERPINF1
- TSPAN1
- FXYD3
- EPCAM
- ELF3
- BEST4
- LYPD2
Multiciliated (non-nasal):
- IGFBP2
- SERPINF1
- TSPAN1
- FXYD3
- EPCAM
- ELF3
- RSPH1
- C20orf85
- C9orf24
Myofibroblasts:
- LUM
- COL6A3
- CFD
- LMOD1
- ATP1B1
- TYRP1
- COL1A2
- DCN
- MFAP4
NK cells:
- CD53
- PTPRC
- CORO1A
- ISG20
- CCL5
- GNLY
- SPON2
- FCGR3A
Neuroendocrine:
- CELF3
- SLC6A17
- CDK5R2
Non-classical monocytes:
- CD53
- PTPRC
- CORO1A
- FCER1G
- C1orf162
- CLEC7A
- MTSS1
- LILRA5
- FCN1
Peribronchial fibroblasts:
- LUM
- COL6A3
- CFD
- COL15A1
- CXCL14
- DIO2
- COL1A2
- DCN
- MFAP4
Pericytes:
- LAMC3
- COL1A2
- DCN
- MFAP4
Plasma cells:
- CD53
- PTPRC
- CORO1A
- TNFRSF17
Plasmacytoid DCs:
- CD53
- PTPRC
- CORO1A
- SCT
- SMPD3
- LILRA4
SM activated stress response:
- EGR1
- FOSB
- ATF3
- MYH11
- TINAGL1
- PLN
- COL1A2
- DCN
- MFAP4
SMG duct:
- FXYD3
- EPCAM
- ELF3
- MGST1
- KRT19
- KLF5
- TCN1
- FAM3D
- CCL28
SMG mucous:
- FXYD3
- EPCAM
- ELF3
- BPIFB2
- MUC5B
- NKX3-1
- TCN1
- FAM3D
- CCL28
SMG serous (bronchial):
- FXYD3
- EPCAM
- ELF3
- RP11-1143G9.4
- S100A1
- PRB3
- TCN1
- FAM3D
- CCL28
SMG serous (nasal):
- FXYD3
- EPCAM
- ELF3
- STATH
- ODAM
- MUC7
- TCN1
- FAM3D
- CCL28
Smooth muscle:
- MYH11
- TINAGL1
- PLN
- COL1A2
- DCN
- MFAP4
Smooth muscle FAM83D+:
- FAM83D
- COL1A2
- DCN
- MFAP4
Subpleural fibroblasts:
- LUM
- COL6A3
- CFD
- COL1A2
- DCN
- MFAP4
- MARCKSL1
- APOC1
- MMP23B
Suprabasal:
- IGFBP2
- SERPINF1
- TSPAN1
- FXYD3
- EPCAM
- ELF3
- KRT5
- SERPINB3
T cells proliferating:
- CD53
- PTPRC
- CORO1A
- ISG20
- CCL5
- CENPW
- TK1
- MKI67
Tuft:
- FXYD3
- EPCAM
- ELF3
- DAB1
pre-TB secretory:
- IGFBP2
- SERPINF1
- TSPAN1
- FXYD3
- EPCAM
- ELF3
- SFTPB
- RNASE1
- SFTA1P
