output_dir: data/pipeline/HLCAv1/QC
images: data/images/HLCAv1/QC

defaults:

  relabel:
    threads: 20

  merge:
    dask: true 
    backed: true
    persist: true
    threads: 20

  split_data:
      key: study
      values:
        - Banovich_Kropski_2020
        - Barbry_Leroy_2020
        - Jain_Misharin_2021
        - Krasnow_2020
        - Lafyatis_Rojas_2019
        - Meyer_2019
        - Misharin_2021
        - Misharin_Budinger_2018
        - Nawijn_2021
        - Seibold_2020
        - Teichmann_Meyer_2019
      dask: true
      backed: true
      threads: 20

  doublets:
    counts: raw/X
    batch: sample
    chunk_size: 100_000
    methods:
      - scrublet
      - doubletdetection

  preprocessing:
    raw_counts: raw/X
    normalize:
      target_sum: 10_000
    highly_variable_genes:
      n_top_genes: 2000
      batch_key: dataset
      dask: true
    assemble:
      - normalize
      - highly_variable_genes
    colors:
      - assay
      - dataset
      - study
      - ann_level_1
      - ann_level_2
      - ann_level_3
      - ann_finest_level
      - scanvi_label
      - majority_reference
      - qc_status
      - lung_condition
      - sex
      - scrublet_score
      - doubletdetection_score
      - n_genes
      - n_counts
      - percent_mito
  
  integration:
    batch: dataset
    label: scanvi_label
    raw_counts: layers/counts
    norm_counts: layers/normcounts
    var_mask:
      - highly_variable
    neighbors:
      n_neighbors: 30
    output_types:
      - embed
    umap_colors:
      - assay
      - dataset
      - study
      - ann_level_1
      - ann_level_2
      - ann_level_3
      - ann_finest_level
      - scanvi_label
      - majority_reference
      - qc_status
      - lung_condition
      - sex
      - scrublet_score
      - doubletdetection_score
      - n_genes
      - n_counts
      - percent_mito
    methods:
      # unintegrated:
      # harmony_pytorch:
      #   n_comps: 50
      #   scale: false
      scvi:
        n_layers: 2
        n_latent: 30
        encode_covariates: true
        deeply_inject_covariates: false
        use_layer_norm: both
        use_batch_norm: none
        gene_likelihood: nb
        max_epochs: 200
        early_stopping: true
        early_stopping_monitor: elbo_validation
        early_stopping_patience: 10
        early_stopping_min_delta: 0.0
        plan_kwargs:
          reduce_lr_on_plateau: true
          lr_patience: 8
          lr_factor: 0.1
          weight_decay: 0.0
      
      scanvi:
        # model paramters
        n_layers: 2
        n_latent: 30
        encode_covariates: true
        deeply_inject_covariates: false
        use_layer_norm: both
        use_batch_norm: none
        gene_likelihood: nb
        
        # scVI trainoing parameters
        max_epochs: 500
        early_stopping: true
        early_stopping_monitor: elbo_validation
        early_stopping_patience: 10
        early_stopping_min_delta: 0.0
        plan_kwargs:
          reduce_lr_on_plateau: true
          lr_patience: 8
          lr_factor: 0.1
          weight_decay: 0.0
        
        # scANVI parameters
        scanvi_max_epochs: 200
        scanvi_early_stopping: true
        scanvi_early_stopping_monitor: validation_accuracy
        scanvi_early_stopping_patience: 10
        scanvi_early_stopping_min_delta: 0.001
        scanvi_plan_kwargs:
          reduce_lr_on_plateau: true
          lr_patience: 8
          lr_factor: 0.1
          weight_decay: 0.0

  clustering:
    algorithm: leiden
    use_gpu: false
    neighbors:
      use_rep: X_emb
      n_neighbors: 30
      metric: euclidean
    resolutions:
      - 0.5
    hierarchy:
      2: 0.2
      3: 0.2
    umap_colors:
      - file_id
      - core_or_extension
      - assay
      - dataset
      - study
      - disease
      - suspension_type
      - ann_level_1
      - ann_level_2
      - ann_level_3
      - ann_finest_level
      - scanvi_label
      - majority_reference
      - qc_status
      - lung_condition
      - sex
      - scrublet_score
      - doubletdetection_score
      - n_genes
      - n_counts
      - percent_mito
      - leiden_3
      - leiden_4
      - majority_reference

  label_transfer:
    majority_reference:
      reference_key: ann_finest_level
      query_key: leiden_0.5_3
      crosstab_kwargs:
        dropna: true

  metrics:
    raw_counts: layers/counts
    unintegrated: layers/normcounts
    var_mask: highly_variable
    clustering:
      precomputed_key: leiden_0.5_3
    parse_file_id: true
    weight_batch: 0.4
    use_scaled: false
    label: ann_finest_level
    batch:
      - dataset
      # - assay
    gene_sets:
      Immune:
        - CD53
        - PTPRC
        - CORO1A
      Alveolar Mph:
        - CYP27A1
        - MARCO
        - FABP4
      T reg:
        - FOXP3
        - RTKN2
      Epithelial:
        - FXYD3
        - EPCAM
        - ELF3
      pre-TB secretory:
        - SCGB1A1 # from Tata paper
        - SFTPB
        - SCGB3A2
        - RNASE1
        - SFTA1P
      AT0:
        - SFTPB
        - SCGB3A2
        - IGFBP2
        - SERPINF1
        - TSPAN1
        - SFTA2
        - C11orf96
      EC:
        - CLDN5
        - ECSCR
        - CLEC14A
      Stroma:
        - COL1A2
        - DCN
        - MFAP4
      Hematopoietic stem cells:
        - CD53
        - PTPRC
        - CORO1A
        - CRHBP
        - SERPINE2
        - MAP7
    metrics:
      - nmi
      - ari
      # - asw_label
      # - asw_batch
      - cell_cycle
      - clisi
      - ilisi
      - graph_connectivity
      - isolated_label_f1
      - pcr_comparison
      - morans_i_genes
      # - pcr
      # - pcr_genes
      - kbet_pg

  marker_genes:
    sample: sample
    layer: layers/normcounts
    marker_genes: immune, epithelial, endothelial, stroma, other
    rank_genes_groups:
      reference: rest
      method: wilcoxon
    plot:
      n_genes: 5