DATASETS:

  prepare_data:
    input:
      relabel:
        HLCAv1: data/pipeline/load_data/download/HLCAv1_core.h5ad
      preprocessing: relabel
      split_data: relabel
    
    relabel:
      rename_obsm_keys:
        X_scanvi_emb: X_emb
      new_columns:
        file: data/input/HLCA_unfiltered_anno.tsv
        index_col: index
        order:
          - index
          - "3'_or_5'"
          - cell_ranger_version
          - cell_viability_%
          - enrichment
          - ensembl_release_reference_genome
          - single_cell_platform
          - anatomical_region_coarse
          - anatomical_region_highest_res
          - Processing_site
      selective_update:
        base_column: ann_finest_level
        new_column: ann_finest_level
        update_map:
          ann_finest_level:
            'Unknown': # remove labels for "Unknown" cells

    split_data:
      key: study
      values:
        - Banovich_Kropski_2020
        - Barbry_Leroy_2020
        - Jain_Misharin_2021
        - Krasnow_2020
        - Lafyatis_Rojas_2019
        - Meyer_2019
        - Misharin_2021
        - Misharin_Budinger_2018
        - Nawijn_2021
        - Seibold_2020
        - Teichmann_Meyer_2019


  QC:
    input:
      doublets:
        Banovich_Kropski_2020: data/pipeline/HLCAv1/QC/split_data/dataset~prepare_data/file_id~relabel:HLCAv1/key~study/value~Banovich_Kropski_2020.zarr
        Barbry_Leroy_2020: data/pipeline/HLCAv1/QC/split_data/dataset~prepare_data/file_id~relabel:HLCAv1/key~study/value~Barbry_Leroy_2020.zarr
        Jain_Misharin_2021: data/pipeline/HLCAv1/QC/split_data/dataset~prepare_data/file_id~relabel:HLCAv1/key~study/value~Jain_Misharin_2021.zarr
        Krasnow_2020: data/pipeline/HLCAv1/QC/split_data/dataset~prepare_data/file_id~relabel:HLCAv1/key~study/value~Krasnow_2020.zarr
        Lafyatis_Rojas_2019: data/pipeline/HLCAv1/QC/split_data/dataset~prepare_data/file_id~relabel:HLCAv1/key~study/value~Lafyatis_Rojas_2019.zarr
        Meyer_2019: data/pipeline/HLCAv1/QC/split_data/dataset~prepare_data/file_id~relabel:HLCAv1/key~study/value~Meyer_2019.zarr
        Misharin_2021: data/pipeline/HLCAv1/QC/split_data/dataset~prepare_data/file_id~relabel:HLCAv1/key~study/value~Misharin_2021.zarr
        Misharin_Budinger_2018: data/pipeline/HLCAv1/QC/split_data/dataset~prepare_data/file_id~relabel:HLCAv1/key~study/value~Misharin_Budinger_2018.zarr
        Nawijn_2021: data/pipeline/HLCAv1/QC/split_data/dataset~prepare_data/file_id~relabel:HLCAv1/key~study/value~Nawijn_2021.zarr
        Seibold_2020: data/pipeline/HLCAv1/QC/split_data/dataset~prepare_data/file_id~relabel:HLCAv1/key~study/value~Seibold_2020.zarr
        Teichmann_Meyer_2019: data/pipeline/HLCAv1/QC/split_data/dataset~prepare_data/file_id~relabel:HLCAv1/key~study/value~Teichmann_Meyer_2019.zarr
      split_data: doublets
      qc: split_data
      merge: qc
    
    split_data:
      fail_on_empty_subset: false
      key: ann_level_1
      values:
        - Immune
        - Epithelial
        - Endothelial
        - Stroma
        # - Proliferating_cells
    
    qc:
      counts: raw/X
      hue:
        - ann_level_2
        - ann_level_3
        # - ann_finest_level
        - assay
        - dataset
        - donor_id
        - fresh_or_frozen
        - reference_genome
        - sequencing_platform
        - scrublet_score
        - doubletdetection_score
      scautoqc_metrics_params: configs/HLCA/QC/scautoqc_params.tsv
      scautoqc_gaussian_kwargs:
        threshold: 0.1
      scautoqc_metrics:
        - n_counts
        - n_genes
        - percent_mito
        - scrublet_score
      # thresholds_file: configs/HLCA/qc_thresholds.tsv

    merge:
      merge_strategy: inner
      dask: true
      backed: true
      threads: 20
      persist: true


  highQC:
    
    ## workflow configuration: what is being run ##

    input:
      # split lowQC and highQC cells
      split_data:
        All: data/pipeline/HLCAv1/QC/merge/dataset~QC.zarr
      preprocessing: split_data

      # de novo integration of highQC data only
      integration: 
        highQC: data/pipeline/HLCAv1/QC/preprocessing/dataset~highQC/file_id~split_data:All--split_data_key=qc_status--split_data_value=passed.zarr
      
      # map low QC back to high QC reference
      reference_mapping:
        lowQC: data/pipeline/HLCAv1/QC/preprocessing/dataset~highQC/file_id~split_data:All--split_data_key=qc_status--split_data_value=failed.zarr
      merge:
        # low QC must go first, otherwise gets overwritten by high QC data
        lowQC: reference_mapping
        highQC: integration
      
      # downstream analyses
      relabel: merge
      clustering: relabel
      label_transfer: clustering
      marker_genes: label_transfer

    
    ## module configuration: how each module is run ##
    
    split_data:
      key: qc_status
      values:
        - failed
        - passed
    
    integration:
      methods:
        scanvi:
          # model parameters
          n_layers: 2
          n_latent: 30
          encode_covariates: true
          deeply_inject_covariates: false
          use_layer_norm: both
          use_batch_norm: none
          gene_likelihood: nb
          
          # scVI training parameters
          max_epochs: 500
          early_stopping: true
          early_stopping_monitor: elbo_validation
          early_stopping_patience: 10
          early_stopping_min_delta: 0.0
          plan_kwargs:
            reduce_lr_on_plateau: true
            lr_patience: 8
            lr_factor: 0.1
            weight_decay: 0.0
          
          # scANVI parameters
          scanvi_max_epochs: 200
          scanvi_early_stopping: true
          scanvi_early_stopping_monitor: validation_accuracy
          scanvi_early_stopping_patience: 10
          scanvi_early_stopping_min_delta: 0.001
          scanvi_plan_kwargs:
            reduce_lr_on_plateau: true
            lr_patience: 8
            lr_factor: 0.1
            weight_decay: 0.0

    reference_mapping:
      scarches:
        model: "data/pipeline/HLCAv1/QC/integration/run_method/dataset~highQC/file_id~highQC\
          /batch~dataset/var_mask~highly_variable/method~scanvi--hyperparams~c4d95b3ea1--label~scanvi_label/model"
        layer: layers/counts
        model_params:
          batch_key: dataset
          freeze_dropout: true
        train_params:
          max_epochs: 500
          early_stopping: true
          early_stopping_monitor: elbo_validation
          early_stopping_patience: 10
          early_stopping_min_delta: 0.001
          plan_kwargs:
            reduce_lr_on_plateau: true
            lr_patience: 8
            lr_factor: 0.1
            weight_decay: 0.0
      umap_colors:
        - file_id
        - ann_finest_level
        - assay
        - dataset
        - study
        - disease
        - lung_condition
        - percent_mito
        - n_counts
        - n_genes
        - scrublet_score
        - doubletdetection_score
        - qc_status

    merge:
      persist: false
      slots:
        obs: obs
        obsm: obsm
        var: var
        X: layers/normcounts

    relabel:
      constant_columns:
        core_or_extension: core
      selective_update:
        base_column: ann_finest_level
        new_column: ann_finest_level_hiqc
        update_map:
          file_id:
            'lowQC': # remove any annotations form low QC dataset

    clustering:
      recompute_umap: true
      recompute_neighbors: true
    
    label_transfer:
      majority_reference:
        reference_key: ann_finest_level_hiqc
        query_key: leiden_0.5_3
        crosstab_kwargs:
          dropna: true

    collect:
      sep: --
      same_slots:
        - X
        - var
        - layers
        - raw
      merge_slots:
        - obsm
        - obs

    marker_genes:
      layer: X
      groups:
        - ann_finest_level
        - majority_reference


  Benchmark_highQC:

    input:
      clustering:
        HLCAv1: data/pipeline/HLCAv1/QC/preprocessing/dataset~prepare_data/file_id~relabel:HLCAv1.zarr
      metrics:
        HLCAv1: clustering
        highQC: data/pipeline/HLCAv1/QC/label_transfer/dataset~highQC/file_id~clustering:relabel:merge:highQC.zarr
    
    clustering:
      recompute_umap: true
      recompute_neighbors: true

    metrics:
      unintegrated: X