DATASETS:

  QC_extended:
    input:
      relabel:
        HLCAv1: data/pipeline/load_data/download/HLCAv1_extended.h5ad
      filter: relabel
      split_data: filter
      doublets: split_data
      qc: doublets
      merge: qc
      preprocessing: merge

    relabel:
      rename_obsm_keys:
        X_scanvi_emb: X_emb
      selective_update:
        base_column: ann_finest_level
        new_column: ann_finest_level
        update_map:
          ann_finest_level:
            'Unknown': # remove labels for "Unknown" cells

    filter:
      dask: true
      backed: true
      keep_by_column:
        core_or_extension:
          - extension

    split_data:
      key: study
      values:
        - Banovich_Kropski_2020
        - Misharin_Budinger_2018
        - Kaminski_2020
        - Meyer_2021
        - Meyer_Nikolic_2022
        - Regev_2021
        - Thienpont_2018
        - Budinger_2020
        - Sheppard_2020
        - Wunderink_2021
        - Lambrechts_2021
        - Zhang_2021
        - Duong_lungMAP_unpubl
        - Janssen_2020
        - Sun_2020
        - Gomperts_2021
        - Eils_2020
        - Schiller_2020
        - Shalek_2018
        - Schiller_2021
        - Peer_Massague_2020
        - Lafyatis_2019
        - Tata_unpubl
        - Xu_2020
        - Sims_2019
        - Schultze_unpubl
    
    clustering:
      algorithm: leiden
      recompute_neighbors: true
      recompute_umap: true
      neighbors:
        use_rep: X_emb
      resolutions: 0.5
      hierarchy: 3

    qc:
      counts: raw/X  
      hue:
        - ann_level_1
        - dataset
        - assay
        - scrublet_score
      scautoqc_metrics:
        - n_counts
        - n_genes
        - percent_mito
        - scrublet_score
      scautoqc_metrics_params: configs/HLCA/QC/scautoqc_params.tsv

    merge:
      slots:
        X: X
        obs: obs
        var: var
        obsm: obsm
      dask: true 
      backed: true
      threads: 50
      persist: true
  
    preprocessing:
      assemble:
        - normalize

  HLCAv1_extended:

    input:
      # query-ref mapping to highQC reference
      reference_mapping:
        QC: data/pipeline/HLCAv1/QC/preprocessing/dataset~QC_extended/file_id~QC_extended.zarr
        # QC: data/pipeline/HLCAv1/QC/preprocessing/dataset~QC_extended/file_id~QC_extended.zarr
      merge:
        extended: reference_mapping
        highQC: data/pipeline/HLCAv1/QC/label_transfer/dataset~highQC/file_id~clustering:relabel:merge:highQC.zarr

      # de-novo integration of original core + extended dataset
      preprocessing:
        HLCAv1: data/pipeline/HLCAv1/QC/relabel/dataset~QC_extended/file_id~HLCAv1.zarr
      integration: preprocessing
      
      # downtsream analyses
      clustering:
        HLCAv1: preprocessing  # HLCA from study
        highQC: merge # query-reference mapping output
        deNovo: integration # de novo integration
      metrics: clustering
      label_transfer: clustering
      collect: label_transfer
      majority_voting: collect
      marker_genes: majority_voting


    ## module configuration: how each module is run ##

    reference_mapping:
      threads: 16
      scarches:
        model: "data/pipeline/HLCAv1/QC/integration/run_method/dataset~highQC/file_id~highQC\
          /batch~dataset/var_mask~highly_variable/method~scanvi--hyperparams~c4d95b3ea1--label~scanvi_label/model"
        layer: layer/counts
        model_params:
          batch_key: dataset
          freeze_dropout: true
        train_params:
          batch_size: 256
          max_epochs: 50
          early_stopping: true
          early_stopping_monitor: elbo_validation
          early_stopping_patience: 15
          early_stopping_min_delta: 0.001
          plan_kwargs:
            reduce_lr_on_plateau: true
            lr_patience: 8
            lr_factor: 0.1
            weight_decay: 0.0
      umap_colors:
        - file_id
        - ann_finest_level
        - assay
        - dataset
        - study
        - disease
        - suspension_type
        - lung_condition
        - percent_mito
        - n_counts
        - n_genes
        - scrublet_score
        - doubletdetection_score
        - qc_status

    merge:
      persist: false
      slots:
        obs: obs
        var: var
        obsm: obsm
        X: X
      keep_all_columns: false

    integration:
      methods:
        scvi:
          n_layers: 2
          n_latent: 30
          encode_covariates: true
          deeply_inject_covariates: false
          use_layer_norm: both
          use_batch_norm: none
          gene_likelihood: nb
          max_epochs: 200
          early_stopping: true
          early_stopping_monitor: elbo_validation
          early_stopping_patience: 10
          early_stopping_min_delta: 0.0
          plan_kwargs:
            reduce_lr_on_plateau: true
            lr_patience: 8
            lr_factor: 0.1
            weight_decay: 0.0

    clustering:
      recompute_neighbors: true
      recompute_umap: true

    metrics:
      unintegrated: X

    collect:
      sep: --
      same_slots:
        - X
        - layers
        - var
      merge_slots:
        - obs
        - obsm
        - obsp
        - uns
    
    majority_voting:
      columns:
        - majority_reference--.*

    marker_genes:
      groups:
        - ann_finest_level
        - majority_consensus
        - majority_reference--label_transfer:clustering:HLCAv1
        - majority_reference--label_transfer:clustering:highQC
        - majority_reference--label_transfer:clustering:deNovo
